### PR TITLE
Update dependencies to allow latest inline-source

### PR DESCRIPTION
**Pull request by ghost**
I'm looking to use the latest version of inline-source from the command line.

Updating the semver range appears to be all that is needed, but I'd like to hear your feedback if possible.

### CODE REVIEW

**Comment by developit** [comment]
Can probably just update to 5, no need to leave it with 4 as well (since its a dep and not a peerDep)

**Comment by ghost** [comment]
Works for me, I didn't want to [tear down a fence without knowing why it was there](https://en.wikipedia.org/wiki/Wikipedia:Chesterton's_fence).

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Good reference 👍

**Comment by ghost** [comment]
Much appreciated!

Could you please publish on NPM so it's available via the registry?  :pray:

**Comment by developit** [comment]
Released as [1.2.0](https://github.com/developit/inline-source-cli/releases/tag/1.2.0)!

**Comment by ghost** [comment]
Thank you, much appreciated.

**Pull request merged**
